### ISSUE TITLE
Thread monitoring container that is stopped is not terminated properly

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/docker-zabbix-sender#1]
Here is the stack I got:
```python
Exception in thread happy_banach:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/docker_zabbix_sender-0.1a-py2.7.egg/docker_zabbix_sender/stats.py", line 63, in run
    for stats in stream:
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.0.0-py2.7.egg/docker/client.py", line 166, in _stream_helper
    data = reader.read(1)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 585, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

**Comment by ggtools** [comment]
Should be fixed by #5
